# Using Pandas

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [2]:
## Your Code here
df = pd.read_csv("data/vehicles.csv")
df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [3]:
## Your Code here

In [4]:
df.describe()

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952.00000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
mean,2000.71640,3.338493,5.765076,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,10.08529,1.359395,1.755268,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,1984.00000,0.600000,2.000000,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,1991.00000,2.200000,4.000000,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,2001.00000,3.000000,6.000000,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,2010.00000,4.300000,6.000000,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,2017.00000,8.400000,16.000000,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

#### Car brand names

In [6]:
df["Make"].value_counts()

Chevrolet                             3643
Ford                                  2946
Dodge                                 2360
GMC                                   2347
Toyota                                1836
BMW                                   1677
Mercedes-Benz                         1284
Nissan                                1253
Volkswagen                            1047
Mitsubishi                             950
Mazda                                  915
Audi                                   890
Porsche                                862
Honda                                  836
Jeep                                   829
Pontiac                                784
Subaru                                 781
Volvo                                  717
Hyundai                                662
Chrysler                               641
Buick                                  537
Mercury                                532
Suzuki                                 512
Cadillac                               508
Kia                                    493
Plymouth                               456
Saab                                   410
Isuzu                                  409
Lexus                                  397
Oldsmobile                             376
Infiniti                               345
Jaguar                                 343
MINI                                   320
Acura                                  302
Saturn                                 278
Lincoln                                273
Ferrari                                208
Rolls-Royce                            160
Eagle                                  156
Geo                                    144
Land Rover                             142
Aston Martin                           133
Bentley                                116
Maserati                               111
Lamborghini                            104
Scion                                   83
Peugeot                                 74
Daewoo                                  67
Ram                                     57
Lotus                                   53
Roush Performance                       53
Fiat                                    43
Alfa Romeo                              41
J.K. Motors                             36
Renault                                 33
Wallace Environmental                   32
Maybach                                 31
American Motors Corporation             22
smart                                   20
Hummer                                  19
Daihatsu                                17
CX Automotive                           16
Merkur                                  14
Federal Coach                           14
McLaren Automotive                      13
Spyker                                  13
Import Trade Services                   13
Sterling                                12
Bugatti                                  8
Yugo                                     8
Genesis                                  7
Tecstar, LP                              6
Mcevoy Motors                            6
Saleen                                   5
VPG                                      5
Bertone                                  5
Autokraft Limited                        4
Saleen Performance                       4
Texas Coach Company                      4
Vector                                   4
Panther Car Company Limited              4
TVR Engineering Ltd                      4
AM General                               4
Grumman Olson                            4
Dacia                                    3
Evans Automobiles                        3
Dabryan Coach Builders Inc               3
Morgan                                   3
Bitter Gmbh and Co. Kg                   3
Consulier Industries Inc                 3
BMW Alpina                               3
Mobility Ventures LLC                    2
Pininfarina                              2
Pagani                                   2
CCC Engineering                          2
SRT                                      2
PAS Inc - GMC                            2
Laforza Automobile Inc                   2
PAS, Inc                                 2
Ruf Automobile Gmbh                      2
Quantum Technologies                     2
Red Shift Ltd.                           2
Bill Dovell Motor Car Company            2
Panoz Auto-Development                   1
Excalibur Autos                          1
Import Foreign Auto Sales Inc            1
JBA Motorcars, Inc.                      1
General Motors                           1
Volga Associated Automobile              1
Panos                                    1
S and S Coach Company  E.p. Dutton       1
Fisker                                   1
Vixen Motor Company                      1
Mahindra                                 1
E. P. Dutton, Inc.                       1
Lambda Control Systems                   1
Grumman Allied Industries                1
Isis Imports Ltd                         1
London Taxi                              1
Environmental Rsch and Devp Corp         1
London Coach Co Inc                      1
Aurora Cars Ltd                          1
ASC Incorporated                         1
Goldacre                                 1
Qvale                                    1
Shelby                                   1
Superior Coaches Div E.p. Dutton         1
Name: Make, dtype: int64

In [7]:
df["Make"].describe()   #there are 127 different brands

count         35952
unique          127
top       Chevrolet
freq           3643
Name: Make, dtype: object

Looking if the are some brand names that refers at the same car

In [8]:
df["Make"].unique()

array(['AM General', 'ASC Incorporated', 'Acura', 'Alfa Romeo',
       'American Motors Corporation', 'Aston Martin', 'Audi',
       'Aurora Cars Ltd', 'Autokraft Limited', 'BMW', 'BMW Alpina',
       'Bentley', 'Bertone', 'Bill Dovell Motor Car Company',
       'Bitter Gmbh and Co. Kg', 'Bugatti', 'Buick', 'CCC Engineering',
       'CX Automotive', 'Cadillac', 'Chevrolet', 'Chrysler',
       'Consulier Industries Inc', 'Dabryan Coach Builders Inc', 'Dacia',
       'Daewoo', 'Daihatsu', 'Dodge', 'E. P. Dutton, Inc.', 'Eagle',
       'Environmental Rsch and Devp Corp', 'Evans Automobiles',
       'Excalibur Autos', 'Federal Coach', 'Ferrari', 'Fiat', 'Fisker',
       'Ford', 'GMC', 'General Motors', 'Genesis', 'Geo', 'Goldacre',
       'Grumman Allied Industries', 'Grumman Olson', 'Honda', 'Hummer',
       'Hyundai', 'Import Foreign Auto Sales Inc',
       'Import Trade Services', 'Infiniti', 'Isis Imports Ltd', 'Isuzu',
       'J.K. Motors', 'JBA Motorcars, Inc.', 'Jaguar', 'Jeep', 'Kia',
       'Laforza Automobile Inc', 'Lambda Control Systems', 'Lamborghini',
       'Land Rover', 'Lexus', 'Lincoln', 'London Coach Co Inc',
       'London Taxi', 'Lotus', 'MINI', 'Mahindra', 'Maserati', 'Maybach',
       'Mazda', 'McLaren Automotive', 'Mcevoy Motors', 'Mercedes-Benz',
       'Mercury', 'Merkur', 'Mitsubishi', 'Mobility Ventures LLC',
       'Morgan', 'Nissan', 'Oldsmobile', 'PAS Inc - GMC', 'PAS, Inc',
       'Pagani', 'Panos', 'Panoz Auto-Development',
       'Panther Car Company Limited', 'Peugeot', 'Pininfarina',
       'Plymouth', 'Pontiac', 'Porsche', 'Quantum Technologies', 'Qvale',
       'Ram', 'Red Shift Ltd.', 'Renault', 'Rolls-Royce',
       'Roush Performance', 'Ruf Automobile Gmbh',
       'S and S Coach Company  E.p. Dutton', 'SRT', 'Saab', 'Saleen',
       'Saleen Performance', 'Saturn', 'Scion', 'Shelby', 'Spyker',
       'Sterling', 'Subaru', 'Superior Coaches Div E.p. Dutton', 'Suzuki',
       'TVR Engineering Ltd', 'Tecstar, LP', 'Texas Coach Company',
       'Toyota', 'VPG', 'Vector', 'Vixen Motor Company',
       'Volga Associated Automobile', 'Volkswagen', 'Volvo',
       'Wallace Environmental', 'Yugo', 'smart'], dtype=object)

In [9]:
#BMW and BMW Alpina
#Dutton
#GMC and General Motors
#PAS Inc - GMC and PAS, Inc
#Saleen and Saleen Performance

In [10]:
df[df["Make"].str.contains("Dutton")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,"E. P. Dutton, Inc.",Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,S and S Coach Company E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Superior Coaches Div E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

In [11]:
df["Make"] = df["Make"].replace(["E. P. Dutton, Inc.",'S and S Coach Company  E.p. Dutton',"Superior Coaches Div E.p. Dutton"], "Dutton")

In [12]:
df[df["Make"].str.contains("Dutton")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,Dutton,Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

It's working! Let's replace the other brands

In [13]:
#BMW and BMW Alpina
df["Make"] = df["Make"].replace(["BMW Alpina"], "BMW")

In [14]:
df[df["Make"].str.contains("BMW")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
1398,BMW,128ci Convertible,2010,3.0,6.0,Automatic (S6),Rear-Wheel Drive,Subcompact Cars,Premium,15.695714,18,27,21,423.190476,1950
1399,BMW,128ci Convertible,2010,3.0,6.0,Manual 6-spd,Rear-Wheel Drive,Subcompact Cars,Premium,14.982273,18,28,22,403.954545,1850
1400,BMW,128ci Convertible,2011,3.0,6.0,Manual 6-spd,Rear-Wheel Drive,Subcompact Cars,Premium,14.982273,18,28,22,403.954545,1850
1401,BMW,128ci Convertible,2011,3.0,6.0,Automatic (S6),Rear-Wheel Drive,Subcompact Cars,Premium,15.695714,18,27,21,423.190476,1950
1402,BMW,128ci Convertible,2012,3.0,6.0,Automatic (S6),Rear-Wheel Drive,Subcompact Cars,Premium,15.695714,18,27,21,423.190476,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3073,BMW,i8,2015,1.5,3.0,Automatic 6-spd,All-Wheel Drive,Subcompact Cars,Premium and Electricity,7.356924,28,29,28,198.000000,1450
3074,BMW,i8,2016,1.5,3.0,Automatic 6-spd,All-Wheel Drive,Subcompact Cars,Premium and Electricity,7.356924,28,29,28,198.000000,1450
3075,BMW,B7,2007,4.4,8.0,Automatic (S6),Rear-Wheel Drive,Large Cars,Premium,20.600625,14,21,16,555.437500,2550
3076,BMW,B7,2008,4.4,8.0,Automatic (S6),Rear-Wheel Drive,Large Cars,Premium,20.600625,14,21,16,555.437500,2550
3077,BMW,Roadster V8,2003,4.8,8.0,Automatic 5-spd,Rear-Wheel Drive,Two Seaters,Premium,21.974000,13,19,15,592.466667,2700

In [15]:
#GMC and General Motors
df["Make"] = df["Make"].replace(["GMC"], "General Motors")

In [16]:
#PAS Inc - GMC and PAS, Inc
df["Make"] = df["Make"].replace(["PAS Inc - GMC", "PAS, Inc" ], "PAS")

In [17]:
#Saleen and Saleen Performance
df["Make"] = df["Make"].replace(["Saleen Performance" ], "Saleen")

In [18]:
df["Make"].describe()  #we have reduce from 127 brands to 121

count         35952
unique          121
top       Chevrolet
freq           3643
Name: Make, dtype: object

- Convert CO2 Emissions from Grams/Mile to Grams/Km

In [19]:
df["CO2 Emission Grams/Km"] = list(map(lambda x:x/1.60934,df["CO2 Emission Grams/Mile"]))
df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

In [20]:
df["Automatic"] = df["Transmission"].apply(lambda x:1 if x.str.startswtih == "Auto")

SyntaxError: invalid syntax (<ipython-input-20-71b570cefdc6>, line 1)

In [21]:
df[df["Transmission"].str.startswith("Auto")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35946,smart,fortwo coupe,2012,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,246.861111,1100,153.392764
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693

In [25]:
df["Automatic"] = np.where(df.Transmission.str.startswith("Auto"), 1, 0)
df["Manual"] = np.where(df.Transmission.str.startswith("Manual"), 1, 0)
df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Automatic,Manual
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736,1,0
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,1,0
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719,1,0
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,1,0
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,1,0
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575,1,0
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,1,0
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693,1,0
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048,0,1

In [ ]:
#df["Automatic"] = np.where(df["Transmission"] == "Auto", 1, 0)
#df["Automatic"] = np.where(df["Transmission"] == "Auto", 1, 0)

In [ ]:
def automatic(row):
    if row.startwith

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [26]:
df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Automatic,Manual
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736,1,0
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,1,0
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719,1,0
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,1,0
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,1,0
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575,1,0
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,1,0
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693,1,0
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048,0,1

In [32]:
#How many car makers are there? How many models? Which car maker has the most cars in the dataset?
df["Make"].describe()

count         35952
unique          121
top       Chevrolet
freq           3643
Name: Make, dtype: object

In [33]:
df["Model"].describe()

count               35952
unique               3608
top       F150 Pickup 2WD
freq                  197
Name: Model, dtype: object

- There are 121 car makers and 3608 models. Chevrolet has the most cars in the dataset

In [34]:
#When were these cars made? --- FROM 1984 TILL 2017

In [37]:
df["Year"].describe()

count    35952.00000
mean      2000.71640
std         10.08529
min       1984.00000
25%       1991.00000
50%       2001.00000
75%       2010.00000
max       2017.00000
Name: Year, dtype: float64

In [ ]:
# How big is the engine of these cars? --- FROM 0.6 till 8.4

In [38]:
df["Engine Displacement"].describe()

count    35952.000000
mean         3.338493
std          1.359395
min          0.600000
25%          2.200000
50%          3.000000
75%          4.300000
max          8.400000
Name: Engine Displacement, dtype: float64

In [39]:
#What's the frequency of different transmissions, drivetrains and fuel types?

In [42]:
df["Transmission"].value_count()

Automatic 4-spd                     10585
Manual 5-spd                         7787
Automatic (S6)                       2631
Automatic 3-spd                      2597
Manual 6-spd                         2423
Automatic 5-spd                      2171
Automatic 6-spd                      1432
Manual 4-spd                         1306
Automatic (S8)                        960
Automatic (S5)                        822
Automatic (variable gear ratios)      675
Automatic 7-spd                       662
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        229
Auto(AM7)                             157
Auto(AV-S6)                           145
Auto(AM6)                             110
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           74
Manual 7-spd                           68
Auto(AV-S7)                            63
Automatic (S9)                         26
Auto(AV-S8)                            26
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Automatic (A1)                          3
Auto(L3)                                2
Auto(L4)                                2
Automatic (AM5)                         2
Auto (AV)                               2
Automatic 6spd                          1
Manual 5 spd                            1
Auto(AM-S9)                             1
Automatic (AM6)                         1
Auto (AV-S6)                            1
Auto (AV-S8)                            1
Auto(A1)                                1
Name: Transmission, dtype: int64

In [43]:
df["Drivetrain"].value_counts()

Front-Wheel Drive             13044
Rear-Wheel Drive              12726
4-Wheel or All-Wheel Drive     6503
All-Wheel Drive                2039
4-Wheel Drive                  1058
2-Wheel Drive                   423
Part-time 4-Wheel Drive         158
2-Wheel Drive, Front              1
Name: Drivetrain, dtype: int64

In [45]:
df["Fuel Type"].value_counts()

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

In [50]:
#What's the car that consumes the least/most fuel?
df[df["Fuel Barrels/Year"]==df["Fuel Barrels/Year"].max()]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Automatic,Manual
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800,788.877073,0,1
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800,788.877073,0,1
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800,788.877073,0,1
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800,788.877073,0,1
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800,788.877073,0,1

In [51]:
df[df["Fuel Barrels/Year"]==df["Fuel Barrels/Year"].min()]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Automatic,Manual
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,27,38,31,228.694355,1000,142.104437,1,0
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,27,38,31,218.000000,1000,135.459257,1,0
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,27,38,31,218.000000,1000,135.459257,1,0
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,27,38,31,218.000000,1000,135.459257,1,0

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [57]:
df["CO2 Emission Grams/Km"].sort_values()

3071      22.990791
3069      24.854909
3070      24.854909
7916      31.690010
7917      31.690010
            ...
20897    788.877073
20894    788.877073
20898    788.877073
20896    788.877073
20895    788.877073
Name: CO2 Emission Grams/Km, Length: 35952, dtype: float64

In [ ]:
df.

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [ ]:
## Your Code is here